name: example
description: A new Eexample project.

version: 1.0.0

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  magic_mirror:
    path: ../magic_mirror

dependency_overrides:
  analyzer: '0.39.17'
  build_resolvers: '1.3.10'
  dart_style: '1.3.6'

dev_dependencies:

  build_runner: ^1.8.0
  build_test: any

  magic_mirror_generator:
    path: ../magic_mirror_generator
#  reflectable: ^2.2.1
#  aym_router_generator:
