name: example
description: A new Eexample project.

version: 1.0.0

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  magic_mirror: ^0.1.0

dependency_overrides:
#  analyzer: '0.39.17'
#  build_resolvers: '1.3.10'
#  dart_style: '1.3.6'
  magic_mirror:
    path: ../magic_mirror
  magic_mirror_generator:
    path: ../magic_mirror_generator

dev_dependencies:

  build_runner: ^1.11.1
  build_test: ^1.3.6

  magic_mirror_generator: ^0.1.0
#  reflectable: ^2.2.1
#  aym_router_generator:
