# Read about `build.yaml` at https://pub.flutter-io.cn/packages/build_config
targets:
  $default:
    builders:
      # The end-user of a builder which applies "source_gen|combining_builder"
      # may configure the builder to ignore specific lints for their project
      magic_mirror_generator|mirror:
        enabled: true
        generate_for:
          - lib/**.dart

builders:
  mirror:
    import: 'package:magic_mirror_generator/src/com/aymtools/mirror/builder.dart'
    builder_factories: [ 'mirror' ]
    build_extensions: { '.dart': [ '.mirror.aymtools.dart' ] }
    auto_apply: root_package
    build_to: source
