name: magic_mirror_generator
description: The core package providing Generators for Class-Information tasks.
version: 0.1.0
homepage: https://github.com/aymtools/magic_mirror

environment:
  sdk: '>=2.8.1 <3.0.0'

#dependencies:
#  path: ^1.7.0

dependencies:
  magic_mirror: ^0.1.0
#    path: ../magic_mirror

  build: ^1.2.2
  dart_style: ^1.3.3
  source_gen: ^0.9.6
  build_resolvers: ^1.3.0

  #  analyzer: 0.39.11
  analyzer: ">=0.39.4 <0.40.0"
  glob: ^1.2.0
  path: ^1.7.0

dev_dependencies:
#  pedantic: ^1.9.0
