name: magic_mirror
description: Contains annotation information and some execution content.Provides reflective actuators, and execution formatting.
version: 0.2.0-dev.2
homepage: https://github.com/aymtools/magic_mirror

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

#dev_dependencies:
#  pedantic: ^1.9.0
